sudo: required #required to use docker
language: java
jdk: openjdk8

before_install:
  - openssl aes-256-cbc -K $encrypted_28c7f3de2fe6_key -iv $encrypted_28c7f3de2fe6_iv -in all.gpg.enc -out ./all.gpg -d
  - gpg --import all.gpg

cache:
  directories:
    - .autoconf
    - $HOME/.m2

services:
  - docker

install:
  - cp .travis.settings.xml $HOME/.m2/settings.xml && mvn clean install

script:
  - echo "no tests!" # put your normal testing scripts here
  - ls -l

deploy:
  provider: script
  script: "cp .travis.settings.xml $HOME/.m2/settings.xml && mvn deploy"
  skip_cleanup: true
  on:
    branch: main

notifications:
  slack: ${env.SLACK_URL_NOTIFICATIONS}