sudo: required
language: java
jdk: openjdk8
before_install:
- openssl aes-256-cbc -K $encrypted_28c7f3de2fe6_key -iv $encrypted_28c7f3de2fe6_iv
  -in all.gpg.enc -out ./all.gpg -d
- gpg --import all.gpg
cache:
  directories:
  - ".autoconf"
  - "$HOME/.m2"
services:
- docker
install:
- cp .travis.settings.xml $HOME/.m2/settings.xml && mvn clean install
deploy:
  provider: script
  script: mvn --settings .travis.settings.xml deploy -Dmaven.test.skip=true
  skip_cleanup: true
  on:
    branch: main
notifications:
  slack: "${env.SLACK_URL_NOTIFICATIONS}"
env:
  global:
  - secure: oH3REdt9ge/A6AeXyHn0mXUqH+yTnix5wdUvGoceUopJ+KkO8ACGTTvhjQdUJMjWyKUAAjW2W/aeZYlMLl5n4q0Tn81CcXQPYP4LykVPLxDqNdxLkURv63QDZ6CxgES3idUg+o2FUp5XTNj2DeVYDtLIed1l3xkIVy8eOuW8HP6JApzgkX4YbjY/y99RGlUUsKfLc8ocnUzqetyIiX2mq4g0+3gUDih0TCqBZPZ0IRR9sjvFmHhzgEUHu3GWVX3RFcAdvG4W819hT4ChVTYvbFoJMEU78LbDC0fWSSwSjhvvkRCew5pyRMPXMh5a1K7bZHq1JQjCxpqv0yqzbwS9jmUK4DjOe6+x0nLRNO0RL4UXJcZ/lwB14/K1TwajGx+mrxYmSdry2yLbz6rhWfNQEfOSTsVHXfSAnTT3g3+QnYI+5JeHkvfJFKn/bsCFCFDr+dP0bPlU4OLiVm8qIUPEPAYuHeKvx1REzo9uGGFJAiISj+2Qy+QqYwoSJyc6oADtSu+esUJhn6pG9lGNTcG+05QMBds6J7xS3btt5/d+4LANN2EBIjkQnuY/xZiGYUVeC+AbtrAC/5Dh8wJ7uzuOLmBH+Jjc0EhFamnloI0NId1jzX2a7O3B7/TyD3r9xI8437WjK++UOQE4rzDRu5if9G3VySow7OdCtB9zsS11P/E=
  - secure: 1cn0nIXMjkcjjhnk9FRr7iGCfCrZ7kzjHW0oAjKL8xSDYLusObFb+2ctAY/0YvwjVM6l1WS7uaI4cG3aN/aHXcDSpQ8J1edN6lYQbOqSG4rkE1menFr3TU87mx6VRSQkR4s8I7fd8Fb6lXFYbaU6/6k4BENL2xCjAxadmWHIJd5W1jK+apFG1OXOb+wN6uCdorWP97lByxQnHZ5hWz7IMSnWzikVt8hFf8WkQIChE0SqzcP0HfNCKGdH6z4BkS3CfE3cOtI1mycLUaWnxhDRCdK+74U98Ssto3Oc2yyGlVnbVNCKBQEpTlOf+8a0W0XXklwvaZnBvzyQwTqCbVyJ/+HkE7fJ/plnmBhSScAR3Y/5Ds09IpNnHe2eB1eDovj7hQkhn30IYXUXQ7TLrlA6GRS2hmuDqV6nY5dpRZMHPotlefTpg86fi/uzWEml/Ic5F8fxrE+TDX7g72BBkZufK/7W1RF0b4fF1HBCcW+u84U2oyME6YHNtfbZ5K4hWrY7CHDRWWu9Of1TOkWUDQ+/OQyB9gANMGOYogyaEJjh15MmYE28C5KfkbpTLDmSuSv6IPvLKQL2pCRChXG/cVM5nHezfQIoWP1C3/2fNJNaC7rOOwVkOjWtmLJT616jO5XItH2OCGVxzaFtyxujlKF4tdm/2RqHwgzvRjcDhgagD1A=
  - secure: FhcH4PtuxkD5I+Z7/CSHWxPBf5MX0VHjt7nGX27qLB5n38n6kaUj4kUcTro+4+4cEvH+EcBDApCkdpvZd5B8sCA/tnriCIIr3Sv1bfPdetKkI+vZjC6NuQx5y9wovJZhqCHBtuZyKNQ94UFNpxW+HB8Qbd1hX0pcxLWV6ages2VoZgqV/rOqlmP/RSrWGEw/x1fsLzT+h3E7vi94fm4ezzl+D+gzLLa+Hlgr4FfnFk80Kpr+df6TBwJqnR9RgXiiwKF15mwAtkxUBA0nLRWCa6jYDgoA0lsTUssIVmb7oDNA2YTRidv84YPPJqdzqOIEfwg4uckxvkyBBA+FMCs+FxxeyD4edE2zEjHNd2h4OXEsmXAbFIS70tO8XpAFCNy8gb4evWcmHttEiIP7PZtSETMxsybXjuHFqaYl2mPJK/J86gBv7rXhs5ze8Ipg1P+E6BRn6DgZz5l+7F2loJYYR7zG5NrPNT4+df9Tq4ZAhU8r0QoV5ZR/+4YC3GYRfsEWwWzU4owSe+N7aNUq5a2EvhtN9x099iyu/WJiqUTnyaiE7VB1qbJmU2JKcQ0221uBwMVL3Ri2PBsmb8R5rqz4XSbroM650AA6bvICm38G0SNlqK01WyfVh9rkLO+u1OGrq3oZ3K/mSimA5rWsweAKyHiFYTW1RmDvGrKTAEcVXIg=
